name: release
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        goos:
          - 'darwin'
          - 'linux'
          - 'windows'
        goarch:
          - 'amd64'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=true"
          dry: true
          changelog-file: changelog.txt
      - name: Get OS and arch info
        if: steps.semrel.outputs.version != ''
        run: |
          GOOS=${{matrix.goos}}
          GOARCH=${{matrix.goarch}}
          BINARY_NAME=timetrack-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV
      - name: Build
        if: steps.semrel.outputs.version != ''
        run: |
          CGO_ENABLED=0 go build -a -ldflags '-s -w' -o "$BINARY_NAME"
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        if: steps.semrel.outputs.version != ''
        with:
          tag_name: v${{ steps.semrel.outputs.version }}
          body_path: changelog.txt
          files: ${{env.BINARY_NAME}}
